# Generated by Django 2.1 on 2020-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbackend', '0002_auto_20200925_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
