# Generated by Django 2.1 on 2020-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbackend', '0003_auto_20200927_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
